#!/usr/bin/env python3
"""Douyin Automation Setup Wizard - Cross-platform path configuration.

Auto-detects douyin-agent project, creator-tools, and generates CONFIG.md.
Works on Windows, macOS, and Linux without hardcoded paths.
"""

import json
import os
import sys
from pathlib import Path

SKILL_DIR = Path(__file__).resolve().parent.parent
CONFIG_FILE = SKILL_DIR / "CONFIG.md"


def find_douyin_home():
    """Auto-detect douyin project directory."""
    home = Path.home()
    candidates = [
        home / "douyin",
        Path("D:/douyin"),
        Path("C:/Users") / home.name / "douyin",
        home / "projects" / "douyin",
        home / "Documents" / "douyin",
        home / "dev" / "douyin",
        home / "code" / "douyin",
    ]
    for c in candidates:
        if c.is_dir() and (c / "douyin-agent-master").exists():
            return c
    # Fallback: just find douyin-agent-master anywhere in home
    for parent in [home, home / "Documents", home / "projects", home / "dev", home / "code"]:
        if not parent.exists():
            continue
        for d in parent.iterdir():
            if d.name == "douyin-agent-master" and d.is_dir():
                return d.parent
    return None


def find_creator_tools():
    """Auto-detect douyin-creator-tools directory."""
    home = Path.home()
    candidates = [
        home / ".openclaw" / "douyin-creator-tools",
        home / ".qclaw" / "douyin-creator-tools",
        home / ".openclaw" / "workspace" / "douyin-creator-tools",
        home / ".qclaw" / "workspace" / "douyin-creator-tools",
    ]
    for c in candidates:
        if c.is_dir():
            return c
    return None


def generate_config(douyin_home, creator_tools=None, cdp_port=9222,
                    agent_port=8080, gateway="http://127.0.0.1:28789"):
    """Generate config dict from base paths."""
    dh = Path(douyin_home)
    agent_backend = dh / "douyin-agent-master" / "backend"
    ct = Path(creator_tools) if creator_tools else Path.home() / ".openclaw" / "douyin-creator-tools"

    return {
        "douyin_home": str(dh),
        "agent_backend": str(agent_backend),
        "orchestrator": str(dh / "orchestrator"),
        "chatgroup_db": str(agent_backend / "app" / "chatgroup.db"),
        "uploads_dir": str(agent_backend / "uploads"),
        "cookies_file": str(agent_backend / "douyin_cookies.json"),
        "creator_tools": str(ct),
        "comments_output": str(ct / "comments-output"),
        "chrome_cdp_port": cdp_port,
        "agent_port": agent_port,
        "openclaw_gateway": gateway,
        "openclaw_model": "openclaw/default",
    }


def write_config_md(config):
    """Write CONFIG.md with the config JSON block."""
    lines = [
        "# Douyin Automation Configuration",
        "",
        "> Auto-generated by `python scripts/setup.py` on "
        f"{__import__('datetime').datetime.now().strftime('%Y-%m-%d %H:%M')}.",
        "> Run `python scripts/setup.py` to reconfigure.",
        "",
        "```json",
        json.dumps(config, indent=2, ensure_ascii=False),
        "```",
        "",
    ]
    CONFIG_FILE.write_text("\n".join(lines), encoding="utf-8")
    return CONFIG_FILE


def validate_config(config):
    """Validate key paths exist. Returns list of (key, path, exists)."""
    checks = []
    for key in ["orchestrator", "chatgroup_db", "creator_tools"]:
        p = Path(config[key])
        checks.append((key, str(p), p.exists()))
    # Optional checks
    for key in ["uploads_dir", "cookies_file"]:
        p = Path(config[key])
        checks.append((key, str(p), p.exists()))
    return checks


def read_existing_config():
    """Read existing CONFIG.md if present."""
    if not CONFIG_FILE.exists():
        return None
    import re
    text = CONFIG_FILE.read_text(encoding="utf-8")
    m = re.search(r"```json\s*([\s\S]*?)\s*```", text)
    if m:
        try:
            return json.loads(m.group(1))
        except json.JSONDecodeError:
            return None
    return None


def main():
    print("=== Douyin Automation Setup ===")
    print(f"OS: {os.name} / {sys.platform}")
    print(f"Home: {Path.home()}")
    print()

    # Load existing config
    existing = read_existing_config()
    if existing:
        print(f"[EXISTING] Found CONFIG.md with douyin_home={existing.get('douyin_home', '?')}")

    # Auto-detect
    douyin_home = find_douyin_home()
    if douyin_home:
        print(f"[AUTO] Found douyin project: {douyin_home}")
    else:
        print("[AUTO] Could not auto-detect douyin project directory.")

    creator_tools = find_creator_tools()
    if creator_tools:
        print(f"[AUTO] Found creator tools: {creator_tools}")

    print()

    # Determine defaults from existing config or auto-detect
    default_dh = str(douyin_home) if douyin_home else (existing.get("douyin_home", "") if existing else "")
    default_ct = str(creator_tools) if creator_tools else (existing.get("creator_tools", "") if existing else "")
    default_cdp = existing.get("chrome_cdp_port", 9222) if existing else 9222
    default_agent = existing.get("agent_port", 8080) if existing else 8080
    default_gw = existing.get("openclaw_gateway", "http://127.0.0.1:28789") if existing else "http://127.0.0.1:28789"

    # Interactive prompts
    dh_input = input(f"Project root [{default_dh or 'REQUIRED'}]: ").strip()
    douyin_home = Path(dh_input) if dh_input else (Path(default_dh) if default_dh else None)

    if not douyin_home:
        print("ERROR: Project root directory is required.")
        print("Download from: https://github.com/HNC87/douyin-automation-skill")
        sys.exit(1)

    ct_input = input(f"Creator tools [{default_ct or 'skip'}]: ").strip()
    creator_tools = Path(ct_input) if ct_input else (Path(default_ct) if default_ct else None)

    cdp_input = input(f"Chrome CDP port [{default_cdp}]: ").strip()
    cdp_port = int(cdp_input) if cdp_input else default_cdp

    agent_input = input(f"Agent API port [{default_agent}]: ").strip()
    agent_port = int(agent_input) if agent_input else default_agent

    gw_input = input(f"OpenClaw Gateway [{default_gw}]: ").strip()
    gateway = gw_input if gw_input else default_gw

    # Generate
    config = generate_config(douyin_home, creator_tools, cdp_port, agent_port, gateway)
    config_file = write_config_md(config)

    print()
    print(f"Config written to: {config_file}")
    print()

    # Validate
    checks = validate_config(config)
    all_ok = True
    for key, path, exists in checks:
        tag = "OK" if exists else "MISSING"
        warn = "" if exists else "  <--"
        print(f"  [{tag}] {key}: {path}{warn}")
        if not exists:
            all_ok = False

    print()
    if all_ok:
        print("All paths validated. Run `python scripts/status-check.py` for full health check.")
    else:
        print("Some paths are missing. Check your douyin-agent setup.")
        print("Download: https://github.com/HNC87/douyin-automation-skill")


if __name__ == "__main__":
    main()
